### ISSUE TITLE
Multiple Commands not working in Project Specific config

### ISSUE THREAD

**Issue by ggedde** [hyperfresh/save-autorun#14]
As the title suggests once I split into multiple commands none of the commands work, but single they do.

This works:
```
'**/*.scss': 'node-sass --source-map true --output-style compressed ${dir}/../master.scss > ${dir}/../min/master.min.css'
```

This does not work for any command:
```
'**/*.scss': [
    'node-sass --source-map true --output-style compressed ${dir}/../master.scss > ${dir}/../min/master.min.css'
    'node-sass --source-map true --output-style compressed ${dir}/../editor-styles.scss > ${dir}/../min/editor-styles.min.css'
]
```

Does multiple commands only work when atom config and not project specific?

**Comment by di97mni** [comment]
I have the same issue

Windows 10:
`C:\Users\martin\.atom\.save.cson`

```
"*": {
    "**/*.adoc": [
        "asciidoctor -r asciidoctor-diagram ${file}"
        "asciidoctor -r asciidoctor-diagram -r asciidoctor-pdf -b pdf ${file}"
      ]
}
```

**Comment by Goodwine** [comment]
Reading the code, this happens because it checks `obj instanceof Object`. Javascript returns `true` for both `[]` and `{}`.
The workaround for this is to use this format:

```cson
'*': {
  '**/*.ts':
    command: [
      'command 1'
      'command 2'
    ]
}
```

Note that there is a race condition and you will see multiple notifications for the last command (if that makes any sense)

**Comment by Goodwine** [comment]
Interesting, the code was fixed a month ago but the maintainer hasn't released this into atom yet.
