### ISSUE TITLE
${path} does not work

### ISSUE THREAD

**Issue by nemzes** [hyperfresh/save-autorun#6]
Tested on OS X Yosemite. Returns `undefined`.

**Comment by bakana808** [comment]
Thanks for making the issue. While I'm no OSX user, but it's strange that it's `undefined`. I'll check it out later on my Windows system but if it's `undefined` it's either from

```
@subscriptions.add atom.workspace.observeTextEditors (textEditor) =>
    @subscriptions.add textEditor.onDidSave (event) => @runDefinitions event['path']
```

if the definitions were run from the save event, or

```
runDefinitions: ->
    textEditor = atom.workspace.getActiveTextEditor()
    if textEditor?
        @runDefinitions textEditor.getPath()
    else
        console.warn ("save-autorun: unable to run save scripts on this pane.")
```

if you ran it from the `save-autorun:execute-definitions` command.

**Comment by nemzes** [comment]
I haven't followed the whole stack, but if it helps:

In `prepareCommand` the `_path` object doesn't have a `filePath` key. It's not `null` or `undefined`, it's simply non-existent. When it is accessed (`save-autorun.coffee`, line 94) it is then evaluated as `undefined`.

**Comment by nemzes** [comment]
Mmmn, actually, shouldn't this line:

```
command = @replaceVar(command, 'path', _path.filePath)
```

Be like this instead?

```
command = @replaceVar(command, 'path', filePath)
```

**Comment by bakana808** [comment]
You may be right. Could you try changing that line and confirming it fixes the problem?

I have a commit ready if it does.

**Comment by nemzes** [comment]
Yep, that makes it work! You might want to remove the note I added to the README.md file, then.  :)

**Comment by bakana808** [comment]
cool, thanks.
